disabled_rules:
- line_length
- trailing_whitespace
- identifier_name
- colon
included:
excluded:
- Pods
- "uso/Protocol/Storyboarded.swift"
- "uso/Cell/HabitList/PlusButtonCell.swift"
- "uso/Extension/Constants.swift"
